# Generated by Django 2.0 on 2019-01-20 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mine', models.CharField(max_length=64)),
                ('whant', models.CharField(max_length=64)),
                ('liaotianbao_id', models.CharField(max_length=128)),
                ('info', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shd.Tags'),
        ),
    ]
